
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
  

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/logs:/app/logs
      - ./backend:/app
    environment:
      - PORT=5000
      - JWTSECRET=hello
      - DB_URL=mongodb://mongodb:27017/toursewa
      - FRONTEND_URL=http://localhost:5173
      - Backend_URL=http://localhost:5000/api
    depends_on:
      - mongodb
    restart: on-failure
    command: ["npm", "start"]

  toursewa:
    build: ./toursewa
    ports:
      - "5173:5173"
    volumes:
      - ./toursewa/src:/app/src
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      - VITE_API_URL=http://backend:5000
    depends_on:
      - backend
    restart: unless-stopped
    command: ["npm", "run", "preview"]
volumes:
  data:
  logs:


